### ISSUE TITLE
Still working in Dec.2018?

### ISSUE THREAD

**Issue by ChikaIke** [anto-christo/webrtc-calling#1]
Hello,

I just tried this tutorial and i have allowed my browser to access my webcam and microphone, but there is no output in the video space. I have tested my webcam on other tools and it works. Please help. I am wondering if Google Chrome no longer allows getUserMedia access in this way anymore?

![notworking](https://user-images.githubusercontent.com/10376735/49730009-58726580-fc77-11e8-9fc3-6c3d71f857b0.PNG)

**Comment by anto-christo** [comment]
Hi, is there any error shown in the developer console of the browser?

**Comment by anto-christo** [comment]
Hi, I know I'm replying very late. The code was not working with modern browsers as you pointed out. And I could not find time to debug it. Today I figured it out and have pushed the updated working code.

In case you still need this, you can check out. Thank you.

Feel free to reopen the issue in case the issue still persists at your end.
